/**
 * Mock Lead Data for Demo
 * 20 realistic emerging artist leads with full enrichment
 */

import type { Lead, LeadSource, LeadStats } from './types';

export const MOCK_LEAD_SOURCES: LeadSource[] = [
  {
    id: 'src-1',
    name: 'Hype Machine - Popular',
    url: 'https://hypem.com/popular',
    sourceType: 'hype_machine',
    crawlFrequency: 'daily',
    lastCrawledAt: new Date().toISOString(),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-2',
    name: 'Bandcamp - New & Notable',
    url: 'https://bandcamp.com/tag/new',
    sourceType: 'bandcamp',
    crawlFrequency: 'daily',
    lastCrawledAt: new Date().toISOString(),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-3',
    name: 'Spotify - Fresh Finds',
    url: 'spotify:playlist:37i9dQZF1DWWjGdmeTyeJ6',
    sourceType: 'spotify_playlist',
    crawlFrequency: 'weekly',
    lastCrawledAt: new Date().toISOString(),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-4',
    name: 'SubmitHub - Trending',
    url: 'https://www.submithub.com/hot-or-not',
    sourceType: 'submithub',
    crawlFrequency: 'daily',
    lastCrawledAt: new Date().toISOString(),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    artistId: null,
    artistName: 'Luna Vale',
    genre: 'Indie Pop / Dream Pop',
    location: 'Los Angeles, USA',
    bio: 'Ethereal soundscapes meet intimate songwriting. Luna Vale crafts dreamy indie pop that has caught the attention of tastemaker blogs worldwide.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Luna+Vale&background=3AA9BE&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example1',
    instagramUrl: 'https://instagram.com/lunavale',
    twitterUrl: 'https://twitter.com/lunavale',
    websiteUrl: 'https://lunavale.com',
    bandcampUrl: 'https://lunavale.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 28500,
    spotifyFollowers: 8200,
    instagramFollowers: 15400,
    twitterFollowers: 3200,
    upcomingReleaseDate: '2025-01-15',
    upcomingReleaseTitle: 'Midnight Garden EP',
    latestReleaseDate: '2024-09-20',
    latestReleaseTitle: 'Velvet Hours',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Upcoming EP in 44 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: 'Hype Machine trending #8', positive: true },
      { type: 'fit', label: 'Dream pop fits Liberty roster', positive: true },
    ],
    aiInsight:
      'Luna Vale shows strong organic growth with 28k monthly listeners and upcoming EP release. No PR representation detected makes this an ideal prospect. Dream pop aesthetic aligns perfectly with Liberty roster artists.',
    aiGeneratedAt: new Date().toISOString(),
    score: 92,
    scoreBreakdown: { timing: 22, momentum: 25, fit: 22, availability: 23 },
    sourceName: 'Hype Machine - Popular',
    sourceType: 'hype_machine',
    sourceRank: 8,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    artistId: null,
    artistName: 'Glass Harbor',
    genre: 'Synth-Pop / Electronic',
    location: 'Berlin, Germany',
    bio: 'Berlin-based synth duo creating pulsing electronic anthems with vintage synths and modern production.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Glass+Harbor&background=8F9BA6&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example2',
    instagramUrl: 'https://instagram.com/glassharbor',
    twitterUrl: null,
    websiteUrl: 'https://glassharbor.de',
    bandcampUrl: 'https://glassharbor.bandcamp.com',
    youtubeUrl: 'https://youtube.com/glassharbor',
    spotifyMonthlyListeners: 45200,
    spotifyFollowers: 12800,
    instagramFollowers: 22100,
    twitterFollowers: null,
    upcomingReleaseDate: '2025-01-08',
    upcomingReleaseTitle: 'Neon Pulse',
    latestReleaseDate: '2024-08-15',
    latestReleaseTitle: 'Chrome Dreams',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unknown',
    signals: [
      { type: 'release', label: 'Single in 37 days', positive: true },
      { type: 'availability', label: 'PR status unknown', positive: true },
      { type: 'momentum', label: '45k monthly listeners', positive: true },
      { type: 'source', label: 'Featured on Fresh Finds', positive: true },
    ],
    aiInsight:
      'Glass Harbor has strong European presence with 45k listeners and growing. Upcoming single timing is perfect for Q1 campaign. Berlin scene credibility adds editorial appeal.',
    aiGeneratedAt: new Date().toISOString(),
    score: 88,
    scoreBreakdown: { timing: 23, momentum: 22, fit: 20, availability: 23 },
    sourceName: 'Spotify - Fresh Finds',
    sourceType: 'spotify_playlist',
    sourceRank: 12,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-3',
    artistId: null,
    artistName: 'Midnight Orchid',
    genre: 'Alternative R&B',
    location: 'Toronto, Canada',
    bio: 'Blending R&B with alternative production, Midnight Orchid creates moody, atmospheric tracks that resonate with late-night listeners.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Midnight+Orchid&background=B4372C&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example3',
    instagramUrl: 'https://instagram.com/midnightorchid',
    twitterUrl: 'https://twitter.com/midnightorchid',
    websiteUrl: null,
    bandcampUrl: null,
    youtubeUrl: 'https://youtube.com/midnightorchid',
    spotifyMonthlyListeners: 67800,
    spotifyFollowers: 18500,
    instagramFollowers: 34200,
    twitterFollowers: 8900,
    upcomingReleaseDate: '2024-12-20',
    upcomingReleaseTitle: 'After Hours',
    latestReleaseDate: '2024-10-05',
    latestReleaseTitle: 'Silhouette',
    hasPrAgency: true,
    prAgencyName: 'Indie Press Co',
    prConfidence: 'likely',
    signals: [
      { type: 'release', label: 'Single in 18 days', positive: true },
      { type: 'momentum', label: '67k monthly listeners', positive: true },
      { type: 'availability', label: 'May have PR (Indie Press Co)', positive: false },
      { type: 'fit', label: 'Alt R&B diversifies roster', positive: true },
    ],
    aiInsight:
      'Strong momentum with 67k listeners but likely has PR representation through Indie Press Co. Could still be worth outreach as contract status unknown. High engagement rates on social.',
    aiGeneratedAt: new Date().toISOString(),
    score: 72,
    scoreBreakdown: { timing: 24, momentum: 25, fit: 18, availability: 5 },
    sourceName: 'Hype Machine - Popular',
    sourceType: 'hype_machine',
    sourceRank: 3,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-4',
    artistId: null,
    artistName: 'Velvet Ruins',
    genre: 'Post-Punk / Darkwave',
    location: 'Manchester, UK',
    bio: 'Dark, brooding post-punk that channels the spirit of Joy Division and Bauhaus with a modern edge.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Velvet+Ruins&background=111111&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example4',
    instagramUrl: 'https://instagram.com/velvetruins',
    twitterUrl: 'https://twitter.com/velvetruins',
    websiteUrl: 'https://velvetruins.co.uk',
    bandcampUrl: 'https://velvetruins.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 12400,
    spotifyFollowers: 4100,
    instagramFollowers: 8700,
    twitterFollowers: 2100,
    upcomingReleaseDate: '2025-02-14',
    upcomingReleaseTitle: 'Shadows & Light LP',
    latestReleaseDate: '2024-06-01',
    latestReleaseTitle: 'Concrete Gardens',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 74 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'fit', label: 'Post-punk fits Liberty sound', positive: true },
      { type: 'source', label: 'Bandcamp Best Seller', positive: true },
    ],
    aiInsight:
      'Velvet Ruins represents the UK post-punk revival with authentic sound and dedicated fanbase. Album campaign opportunity with no PR detected. Strong Bandcamp sales indicate engaged audience.',
    aiGeneratedAt: new Date().toISOString(),
    score: 85,
    scoreBreakdown: { timing: 15, momentum: 20, fit: 25, availability: 25 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 5,
    status: 'pipeline',
    statusUpdatedAt: new Date(Date.now() - 3600000).toISOString(),
    statusUpdatedBy: 'Sarah Mitchell',
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-5',
    artistId: null,
    artistName: 'Solar Flare',
    genre: 'Indie Rock',
    location: 'Melbourne, Australia',
    bio: 'Sun-drenched indie rock from Down Under. Solar Flare brings warmth and energy to every track.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Solar+Flare&background=F59E0B&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example5',
    instagramUrl: 'https://instagram.com/solarflareband',
    twitterUrl: null,
    websiteUrl: 'https://solarflaremusic.com.au',
    bandcampUrl: null,
    youtubeUrl: 'https://youtube.com/solarflareband',
    spotifyMonthlyListeners: 19800,
    spotifyFollowers: 5600,
    instagramFollowers: 11200,
    twitterFollowers: null,
    upcomingReleaseDate: '2025-01-24',
    upcomingReleaseTitle: 'Golden Hour',
    latestReleaseDate: '2024-07-12',
    latestReleaseTitle: 'Summer Haze',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Single in 53 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: 'Growing AU fanbase', positive: true },
      { type: 'fit', label: 'Indie rock core genre', positive: true },
    ],
    aiInsight:
      'Solar Flare has strong Australian base with 20k listeners and international touring aspirations. No PR representation makes this a clean outreach opportunity for Q1 campaign.',
    aiGeneratedAt: new Date().toISOString(),
    score: 81,
    scoreBreakdown: { timing: 18, momentum: 18, fit: 22, availability: 23 },
    sourceName: 'SubmitHub - Trending',
    sourceType: 'submithub',
    sourceRank: 15,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-6',
    artistId: null,
    artistName: 'Neon Vespers',
    genre: 'Shoegaze / Dream Pop',
    location: 'Portland, USA',
    bio: 'Layered guitars and ethereal vocals create immersive sonic landscapes inspired by 90s shoegaze.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Neon+Vespers&background=A855F7&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example6',
    instagramUrl: 'https://instagram.com/neonvespers',
    twitterUrl: 'https://twitter.com/neonvespers',
    websiteUrl: null,
    bandcampUrl: 'https://neonvespers.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 8900,
    spotifyFollowers: 2800,
    instagramFollowers: 6500,
    twitterFollowers: 1400,
    upcomingReleaseDate: '2025-01-31',
    upcomingReleaseTitle: 'Hollow Light',
    latestReleaseDate: '2024-04-20',
    latestReleaseTitle: 'Fading Echoes',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'EP in 60 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'source', label: 'Bandcamp staff pick', positive: true },
      { type: 'fit', label: 'Shoegaze niche appeal', positive: true },
    ],
    aiInsight:
      'Neon Vespers has dedicated shoegaze following with strong Bandcamp presence. Smaller numbers but highly engaged audience. EP release timing works for February push.',
    aiGeneratedAt: new Date().toISOString(),
    score: 78,
    scoreBreakdown: { timing: 17, momentum: 14, fit: 22, availability: 25 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 8,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-7',
    artistId: null,
    artistName: 'Crystal Waves',
    genre: 'Chillwave / Electronic',
    location: 'Tokyo, Japan',
    bio: 'Blending Japanese city pop influences with modern electronic production for a unique chillwave sound.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Crystal+Waves&background=EC4899&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example7',
    instagramUrl: 'https://instagram.com/crystalwavesmusic',
    twitterUrl: 'https://twitter.com/crystalwaves_jp',
    websiteUrl: 'https://crystalwaves.jp',
    bandcampUrl: null,
    youtubeUrl: 'https://youtube.com/crystalwaves',
    spotifyMonthlyListeners: 52300,
    spotifyFollowers: 14200,
    instagramFollowers: 28900,
    twitterFollowers: 12400,
    upcomingReleaseDate: '2025-01-10',
    upcomingReleaseTitle: 'Tokyo Nights',
    latestReleaseDate: '2024-11-01',
    latestReleaseTitle: 'Shibuya Dreams',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unknown',
    signals: [
      { type: 'release', label: 'Album in 39 days', positive: true },
      { type: 'momentum', label: '52k monthly listeners', positive: true },
      { type: 'availability', label: 'No Western PR', positive: true },
      { type: 'fit', label: 'Unique cultural angle', positive: true },
    ],
    aiInsight:
      'Crystal Waves offers unique Japanese city pop crossover appeal with strong streaming numbers. No Western PR representation detected - opportunity for international expansion campaign.',
    aiGeneratedAt: new Date().toISOString(),
    score: 86,
    scoreBreakdown: { timing: 21, momentum: 23, fit: 20, availability: 22 },
    sourceName: 'Spotify - Fresh Finds',
    sourceType: 'spotify_playlist',
    sourceRank: 7,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-8',
    artistId: null,
    artistName: 'Hollow Pine',
    genre: 'Folk / Americana',
    location: 'Nashville, USA',
    bio: 'Authentic Americana storytelling with fingerpicked guitars and haunting harmonies.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Hollow+Pine&background=22C55E&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example8',
    instagramUrl: 'https://instagram.com/hollowpine',
    twitterUrl: null,
    websiteUrl: 'https://hollowpinemusic.com',
    bandcampUrl: 'https://hollowpine.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 15600,
    spotifyFollowers: 4800,
    instagramFollowers: 9200,
    twitterFollowers: null,
    upcomingReleaseDate: '2025-02-28',
    upcomingReleaseTitle: 'Mountain Songs',
    latestReleaseDate: '2024-03-15',
    latestReleaseTitle: 'River Road',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 88 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: 'Growing folk scene buzz', positive: true },
      { type: 'fit', label: 'Americana crossover potential', positive: true },
    ],
    aiInsight:
      'Hollow Pine represents authentic Americana with Nashville credibility. Album campaign opportunity for Q1. Strong songwriting could appeal to folk blogs and roots radio.',
    aiGeneratedAt: new Date().toISOString(),
    score: 74,
    scoreBreakdown: { timing: 12, momentum: 17, fit: 20, availability: 25 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 12,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 691200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-9',
    artistId: null,
    artistName: 'Static Heart',
    genre: 'Indie Electronic',
    location: 'Stockholm, Sweden',
    bio: 'Swedish duo crafting melancholic electronic pop with introspective lyrics and cinematic production.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Static+Heart&background=3AA9BE&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example9',
    instagramUrl: 'https://instagram.com/staticheartmusic',
    twitterUrl: 'https://twitter.com/staticheart_se',
    websiteUrl: 'https://staticheart.se',
    bandcampUrl: null,
    youtubeUrl: 'https://youtube.com/staticheart',
    spotifyMonthlyListeners: 38700,
    spotifyFollowers: 11200,
    instagramFollowers: 19800,
    twitterFollowers: 5600,
    upcomingReleaseDate: '2024-12-27',
    upcomingReleaseTitle: 'Winter Light',
    latestReleaseDate: '2024-09-01',
    latestReleaseTitle: 'Autumn Fade',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Single in 25 days', positive: true },
      { type: 'momentum', label: '38k monthly listeners', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'source', label: 'Hype Machine trending', positive: true },
    ],
    aiInsight:
      'Static Heart has strong Nordic electronic sound with 38k listeners. Imminent single release perfect for holiday campaign. Swedish acts have strong editorial appeal.',
    aiGeneratedAt: new Date().toISOString(),
    score: 89,
    scoreBreakdown: { timing: 24, momentum: 22, fit: 20, availability: 23 },
    sourceName: 'Hype Machine - Popular',
    sourceType: 'hype_machine',
    sourceRank: 5,
    status: 'pipeline',
    statusUpdatedAt: new Date(Date.now() - 7200000).toISOString(),
    statusUpdatedBy: 'James Cooper',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-10',
    artistId: null,
    artistName: 'Rust & Gold',
    genre: 'Alt-Country / Indie Folk',
    location: 'Austin, USA',
    bio: 'Austin-based quartet blending alt-country grit with indie folk sensitivity.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Rust+Gold&background=EAB308&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example10',
    instagramUrl: 'https://instagram.com/rustandgoldband',
    twitterUrl: 'https://twitter.com/rustandgold',
    websiteUrl: null,
    bandcampUrl: 'https://rustandgold.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 7200,
    spotifyFollowers: 2100,
    instagramFollowers: 5400,
    twitterFollowers: 980,
    upcomingReleaseDate: '2025-03-14',
    upcomingReleaseTitle: 'Dusty Trails EP',
    latestReleaseDate: '2024-05-20',
    latestReleaseTitle: 'Highway Hymns',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'EP in 103 days', positive: false },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: 'Growing Austin scene', positive: true },
      { type: 'fit', label: 'Alt-country niche', positive: true },
    ],
    aiInsight:
      'Rust & Gold has authentic Austin credibility but smaller numbers. EP release timing is far out - better for later quarter consideration. Strong live reputation could drive campaign.',
    aiGeneratedAt: new Date().toISOString(),
    score: 62,
    scoreBreakdown: { timing: 8, momentum: 12, fit: 18, availability: 24 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 22,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 777600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-11',
    artistId: null,
    artistName: 'Echo Chamber',
    genre: 'Post-Rock / Ambient',
    location: 'Glasgow, UK',
    bio: 'Instrumental post-rock from Glasgow, building from whispers to walls of sound.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Echo+Chamber&background=737373&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example11',
    instagramUrl: 'https://instagram.com/echochamberband',
    twitterUrl: null,
    websiteUrl: 'https://echochamber.scot',
    bandcampUrl: 'https://echochamber.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 24100,
    spotifyFollowers: 7800,
    instagramFollowers: 12300,
    twitterFollowers: null,
    upcomingReleaseDate: '2025-01-17',
    upcomingReleaseTitle: 'Signals From Afar',
    latestReleaseDate: '2024-08-30',
    latestReleaseTitle: 'Distant Shores',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 46 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: '24k monthly listeners', positive: true },
      { type: 'fit', label: 'Post-rock press appeal', positive: true },
    ],
    aiInsight:
      "Echo Chamber represents Glasgow's vibrant post-rock scene with strong album incoming. No PR detected and good streaming numbers make this ideal for campaign.",
    aiGeneratedAt: new Date().toISOString(),
    score: 84,
    scoreBreakdown: { timing: 20, momentum: 20, fit: 22, availability: 22 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 6,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-12',
    artistId: null,
    artistName: 'Satin Dusk',
    genre: 'Neo-Soul / R&B',
    location: 'London, UK',
    bio: 'London-based neo-soul artist blending classic soul influences with contemporary R&B production.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Satin+Dusk&background=EC4899&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example12',
    instagramUrl: 'https://instagram.com/satinduskmusic',
    twitterUrl: 'https://twitter.com/satindusk',
    websiteUrl: null,
    bandcampUrl: null,
    youtubeUrl: 'https://youtube.com/satindusk',
    spotifyMonthlyListeners: 42800,
    spotifyFollowers: 13500,
    instagramFollowers: 31200,
    twitterFollowers: 8700,
    upcomingReleaseDate: '2024-12-13',
    upcomingReleaseTitle: 'Velvet Nights',
    latestReleaseDate: '2024-10-18',
    latestReleaseTitle: 'Golden Hour',
    hasPrAgency: true,
    prAgencyName: null,
    prConfidence: 'likely',
    signals: [
      { type: 'release', label: 'Single in 11 days', positive: true },
      { type: 'momentum', label: '42k monthly listeners', positive: true },
      { type: 'availability', label: 'Likely has PR', positive: false },
      { type: 'fit', label: 'Neo-soul market growing', positive: true },
    ],
    aiInsight:
      'Satin Dusk has strong momentum with 42k listeners and imminent release. However, activity patterns suggest existing PR representation. Worth monitoring for contract end.',
    aiGeneratedAt: new Date().toISOString(),
    score: 68,
    scoreBreakdown: { timing: 25, momentum: 23, fit: 15, availability: 5 },
    sourceName: 'Hype Machine - Popular',
    sourceType: 'hype_machine',
    sourceRank: 4,
    status: 'dismissed',
    statusUpdatedAt: new Date(Date.now() - 14400000).toISOString(),
    statusUpdatedBy: 'Sarah Mitchell',
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-13',
    artistId: null,
    artistName: 'Binary Sunset',
    genre: 'Synthwave / Retrowave',
    location: 'Paris, France',
    bio: 'French synthwave producer creating nostalgic 80s-inspired electronic soundscapes.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Binary+Sunset&background=F59E0B&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example13',
    instagramUrl: 'https://instagram.com/binarysunset',
    twitterUrl: 'https://twitter.com/binarysunset_fr',
    websiteUrl: 'https://binarysunset.fr',
    bandcampUrl: 'https://binarysunset.bandcamp.com',
    youtubeUrl: 'https://youtube.com/binarysunset',
    spotifyMonthlyListeners: 31500,
    spotifyFollowers: 9200,
    instagramFollowers: 15800,
    twitterFollowers: 4200,
    upcomingReleaseDate: '2025-02-07',
    upcomingReleaseTitle: 'Neon Horizon',
    latestReleaseDate: '2024-07-28',
    latestReleaseTitle: 'Midnight Drive',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 67 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: '31k monthly listeners', positive: true },
      { type: 'fit', label: 'Synthwave growing genre', positive: true },
    ],
    aiInsight:
      'Binary Sunset has established synthwave audience with 31k listeners. Album release timing works for Q1 push. French electronic acts have strong European press appeal.',
    aiGeneratedAt: new Date().toISOString(),
    score: 79,
    scoreBreakdown: { timing: 16, momentum: 20, fit: 20, availability: 23 },
    sourceName: 'Spotify - Fresh Finds',
    sourceType: 'spotify_playlist',
    sourceRank: 18,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-14',
    artistId: null,
    artistName: 'Violet Hours',
    genre: 'Chamber Pop / Art Pop',
    location: 'Brooklyn, USA',
    bio: 'Brooklyn art pop collective creating orchestral arrangements with indie sensibilities.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Violet+Hours&background=A855F7&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example14',
    instagramUrl: 'https://instagram.com/violethours',
    twitterUrl: 'https://twitter.com/violethoursnyc',
    websiteUrl: 'https://violethours.nyc',
    bandcampUrl: 'https://violethours.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 16200,
    spotifyFollowers: 5100,
    instagramFollowers: 10800,
    twitterFollowers: 3200,
    upcomingReleaseDate: '2025-01-03',
    upcomingReleaseTitle: 'Orchestral Dreams',
    latestReleaseDate: '2024-06-14',
    latestReleaseTitle: 'Symphony for the Lost',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unknown',
    signals: [
      { type: 'release', label: 'Album in 32 days', positive: true },
      { type: 'availability', label: 'PR status unknown', positive: true },
      { type: 'momentum', label: 'Critical acclaim growing', positive: true },
      { type: 'fit', label: 'Art pop editorial appeal', positive: true },
    ],
    aiInsight:
      'Violet Hours creates ambitious chamber pop with strong critical reception. Album timing perfect for January release. Art pop aesthetic appeals to quality publications.',
    aiGeneratedAt: new Date().toISOString(),
    score: 82,
    scoreBreakdown: { timing: 22, momentum: 18, fit: 22, availability: 20 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 3,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-15',
    artistId: null,
    artistName: 'Frost & Fire',
    genre: 'Nordic Folk / Ambient',
    location: 'Reykjavik, Iceland',
    bio: 'Icelandic duo blending traditional Nordic folk with ambient electronic textures.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Frost+Fire&background=3AA9BE&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example15',
    instagramUrl: 'https://instagram.com/frostandfire',
    twitterUrl: null,
    websiteUrl: 'https://frostandfire.is',
    bandcampUrl: 'https://frostandfire.bandcamp.com',
    youtubeUrl: 'https://youtube.com/frostandfire',
    spotifyMonthlyListeners: 58900,
    spotifyFollowers: 16800,
    instagramFollowers: 24500,
    twitterFollowers: null,
    upcomingReleaseDate: '2025-01-20',
    upcomingReleaseTitle: 'Northern Lights',
    latestReleaseDate: '2024-10-01',
    latestReleaseTitle: 'Aurora',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 49 days', positive: true },
      { type: 'momentum', label: '58k monthly listeners', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'source', label: 'Spotify editorial adds', positive: true },
    ],
    aiInsight:
      'Frost & Fire has exceptional numbers for Nordic folk genre with 58k listeners. Icelandic origin adds mystique and editorial appeal. Album timing perfect for winter campaign.',
    aiGeneratedAt: new Date().toISOString(),
    score: 91,
    scoreBreakdown: { timing: 21, momentum: 25, fit: 22, availability: 23 },
    sourceName: 'Spotify - Fresh Finds',
    sourceType: 'spotify_playlist',
    sourceRank: 4,
    status: 'pipeline',
    statusUpdatedAt: new Date(Date.now() - 1800000).toISOString(),
    statusUpdatedBy: 'Sarah Mitchell',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-16',
    artistId: null,
    artistName: 'Pale Monarch',
    genre: 'Indie Rock / Psych Rock',
    location: 'Dublin, Ireland',
    bio: 'Dublin psych-rock outfit channeling krautrock influences with modern indie sensibilities.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Pale+Monarch&background=8F9BA6&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example16',
    instagramUrl: 'https://instagram.com/palemonarch',
    twitterUrl: 'https://twitter.com/palemonarch',
    websiteUrl: null,
    bandcampUrl: 'https://palemonarch.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 11800,
    spotifyFollowers: 3600,
    instagramFollowers: 7200,
    twitterFollowers: 1800,
    upcomingReleaseDate: '2025-02-21',
    upcomingReleaseTitle: 'Cosmic Debris',
    latestReleaseDate: '2024-04-05',
    latestReleaseTitle: 'Astral Plane',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 81 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'fit', label: 'Irish psych rock scene', positive: true },
      { type: 'momentum', label: 'Growing cult following', positive: true },
    ],
    aiInsight:
      "Pale Monarch represents Dublin's psych-rock revival with dedicated following. Album campaign opportunity with no PR competition. Irish acts have strong UK/EU press networks.",
    aiGeneratedAt: new Date().toISOString(),
    score: 76,
    scoreBreakdown: { timing: 14, momentum: 16, fit: 22, availability: 24 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 11,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-17',
    artistId: null,
    artistName: 'Silver Tide',
    genre: 'Indie Pop / Bedroom Pop',
    location: 'Vancouver, Canada',
    bio: 'Lo-fi bedroom pop crafted in a Vancouver apartment, finding beauty in imperfection.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Silver+Tide&background=22C55E&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example17',
    instagramUrl: 'https://instagram.com/silvertidemusic',
    twitterUrl: 'https://twitter.com/silvertide_',
    websiteUrl: null,
    bandcampUrl: 'https://silvertide.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 22400,
    spotifyFollowers: 6800,
    instagramFollowers: 14500,
    twitterFollowers: 3900,
    upcomingReleaseDate: '2025-01-05',
    upcomingReleaseTitle: 'Daydream Haze',
    latestReleaseDate: '2024-09-12',
    latestReleaseTitle: 'Quiet Moments',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'EP in 34 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: '22k monthly listeners', positive: true },
      { type: 'fit', label: 'Bedroom pop trending', positive: true },
    ],
    aiInsight:
      'Silver Tide has strong bedroom pop aesthetic with 22k engaged listeners. EP timing perfect for January push. Genre is highly shareable on social platforms.',
    aiGeneratedAt: new Date().toISOString(),
    score: 83,
    scoreBreakdown: { timing: 21, momentum: 19, fit: 20, availability: 23 },
    sourceName: 'SubmitHub - Trending',
    sourceType: 'submithub',
    sourceRank: 8,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-18',
    artistId: null,
    artistName: 'Copper & Lace',
    genre: 'Folk Pop / Singer-Songwriter',
    location: 'Bristol, UK',
    bio: 'Bristol folk duo weaving intricate harmonies with contemporary folk-pop production.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Copper+Lace&background=B4372C&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example18',
    instagramUrl: 'https://instagram.com/copperandlace',
    twitterUrl: 'https://twitter.com/copperandlace',
    websiteUrl: 'https://copperandlace.co.uk',
    bandcampUrl: null,
    youtubeUrl: 'https://youtube.com/copperandlace',
    spotifyMonthlyListeners: 9500,
    spotifyFollowers: 2900,
    instagramFollowers: 6100,
    twitterFollowers: 1500,
    upcomingReleaseDate: '2025-02-01',
    upcomingReleaseTitle: 'Woven Tales',
    latestReleaseDate: '2024-05-10',
    latestReleaseTitle: 'Golden Thread',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'EP in 61 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'fit', label: 'Folk pop market stable', positive: true },
      { type: 'momentum', label: 'Bristol scene support', positive: true },
    ],
    aiInsight:
      'Copper & Lace has authentic folk-pop sound with Bristol scene credibility. EP release timing works for February campaign. Duo format offers visual and press appeal.',
    aiGeneratedAt: new Date().toISOString(),
    score: 73,
    scoreBreakdown: { timing: 17, momentum: 14, fit: 19, availability: 23 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 14,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 691200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-19',
    artistId: null,
    artistName: 'Phantom Circuit',
    genre: 'Industrial / Electronic',
    location: 'Detroit, USA',
    bio: 'Detroit industrial producer creating dark, pounding electronic music with techno influences.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Phantom+Circuit&background=111111&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example19',
    instagramUrl: 'https://instagram.com/phantomcircuit',
    twitterUrl: 'https://twitter.com/phantomcircuit',
    websiteUrl: 'https://phantomcircuit.net',
    bandcampUrl: 'https://phantomcircuit.bandcamp.com',
    youtubeUrl: 'https://youtube.com/phantomcircuit',
    spotifyMonthlyListeners: 28900,
    spotifyFollowers: 8400,
    instagramFollowers: 16700,
    twitterFollowers: 5200,
    upcomingReleaseDate: '2025-01-12',
    upcomingReleaseTitle: 'System Override',
    latestReleaseDate: '2024-08-22',
    latestReleaseTitle: 'Binary Code',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 41 days', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'momentum', label: '28k monthly listeners', positive: true },
      { type: 'source', label: 'Detroit techno credibility', positive: true },
    ],
    aiInsight:
      'Phantom Circuit carries Detroit techno credibility with industrial edge. Album timing works for January push. Niche but dedicated audience with strong engagement.',
    aiGeneratedAt: new Date().toISOString(),
    score: 80,
    scoreBreakdown: { timing: 20, momentum: 19, fit: 18, availability: 23 },
    sourceName: 'Bandcamp - New & Notable',
    sourceType: 'bandcamp',
    sourceRank: 7,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-20',
    artistId: null,
    artistName: 'Autumn Parish',
    genre: 'Indie Folk / Acoustic',
    location: 'Copenhagen, Denmark',
    bio: 'Danish singer-songwriter creating intimate acoustic folk with Scandinavian melancholy.',
    imageUrl:
      'https://ui-avatars.com/api/?name=Autumn+Parish&background=737373&color=fff&size=256&bold=true',
    spotifyUrl: 'https://open.spotify.com/artist/example20',
    instagramUrl: 'https://instagram.com/autumnparish',
    twitterUrl: null,
    websiteUrl: 'https://autumnparish.dk',
    bandcampUrl: 'https://autumnparish.bandcamp.com',
    youtubeUrl: null,
    spotifyMonthlyListeners: 35600,
    spotifyFollowers: 10200,
    instagramFollowers: 18900,
    twitterFollowers: null,
    upcomingReleaseDate: '2024-12-20',
    upcomingReleaseTitle: 'Winter Songs',
    latestReleaseDate: '2024-06-28',
    latestReleaseTitle: 'Summer End',
    hasPrAgency: false,
    prAgencyName: null,
    prConfidence: 'unlikely',
    signals: [
      { type: 'release', label: 'Album in 18 days', positive: true },
      { type: 'momentum', label: '35k monthly listeners', positive: true },
      { type: 'availability', label: 'No PR detected', positive: true },
      { type: 'fit', label: 'Scandinavian folk appeal', positive: true },
    ],
    aiInsight:
      'Autumn Parish has strong Scandinavian folk presence with 35k listeners. Imminent winter-themed album is perfectly timed. Danish acts have growing international appeal.',
    aiGeneratedAt: new Date().toISOString(),
    score: 87,
    scoreBreakdown: { timing: 24, momentum: 21, fit: 20, availability: 22 },
    sourceName: 'Spotify - Fresh Finds',
    sourceType: 'spotify_playlist',
    sourceRank: 9,
    status: 'new',
    statusUpdatedAt: null,
    statusUpdatedBy: null,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Generate stats from mock data
export function getMockLeadStats(): LeadStats {
  const now = new Date();
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  const newLeads = MOCK_LEADS.filter(l => l.status === 'new').length;
  const pipelineLeads = MOCK_LEADS.filter(l => l.status === 'pipeline').length;
  const dismissedLeads = MOCK_LEADS.filter(l => l.status === 'dismissed').length;
  const contactedLeads = MOCK_LEADS.filter(l => l.status === 'contacted').length;

  const totalScore = MOCK_LEADS.reduce((sum, l) => sum + l.score, 0);
  const averageScore = Math.round(totalScore / MOCK_LEADS.length);

  const highScoreLeads = MOCK_LEADS.filter(l => l.score >= 80).length;

  const leadsBySource: Record<string, number> = {};
  MOCK_LEADS.forEach(l => {
    leadsBySource[l.sourceType] = (leadsBySource[l.sourceType] || 0) + 1;
  });

  const leadsThisWeek = MOCK_LEADS.filter(l => new Date(l.createdAt) >= oneWeekAgo).length;

  return {
    totalLeads: MOCK_LEADS.length,
    newLeads,
    pipelineLeads,
    dismissedLeads,
    contactedLeads,
    averageScore,
    highScoreLeads,
    leadsBySource,
    leadsThisWeek,
  };
}
