packages:
  # Active production apps
  - 'apps/audio-intel'
  - 'apps/pitch-generator'
  - 'apps/tracker'
  - 'apps/web'
  # Command centre for MeshOS and internal tools
  - 'apps/command-centre'

  # Removed apps with build errors, unused, or personal
  # - 'apps/api'  # Has TypeScript errors, not in production
  # - 'apps/mobile'  # Security vulnerabilities
  # - 'apps/tap-saas-template-DO-NOT-DELETE'  # Unused template

  # Shared packages
  - 'packages/*'

  # Exclude archived and node_modules
  - '!archive/**'
  - '!**/node_modules/**'
