packages:
  # Active production apps
  - 'apps/audio-intel'
  - 'apps/pitch-generator'
  - 'apps/tracker'
  - 'apps/tap-dashboard'  # Unified Intelligence Dashboard
  # Removed apps with build errors, unused, or personal
  # - 'apps/web'  # Removed - has build errors, will move to separate repo for landing page
  # - 'apps/api'  # Has TypeScript errors, not in production
  # - 'apps/mobile'  # Security vulnerabilities
  # - 'apps/tap-saas-template-DO-NOT-DELETE'  # Unused template
  # - 'apps/command-centre'  # Personal productivity app (excluded from CI)

  # Shared packages
  - 'packages/*'

  # Exclude archived and node_modules
  - '!archive/**'
  - '!**/node_modules/**'
