packages:
  # Active production apps
  - 'apps/audio-intel'
  - 'apps/pitch-generator'
  - 'apps/tracker'
  - 'apps/tap-dashboard'
  - 'apps/liberty-demo'
  # - 'apps/web'  # Removed to simplify deployments
  # Removed apps with build errors, unused, or personal
  # - 'apps/api'  # Has TypeScript errors, not in production
  # - 'apps/mobile'  # Security vulnerabilities
  # - 'apps/tap-saas-template-DO-NOT-DELETE'  # Unused template
  # - 'apps/command-centre'  # Personal productivity app (excluded from CI)

  # Shared packages
  - 'packages/*'

  # Exclude archived and node_modules
  - '!archive/**'
  - '!**/node_modules/**'
