// All the JS is generated by AI (Claude Sonnet 4)
// JS is lightly edited by human to redirect on success/failure.
/** @type {'not_available'|'requesting'|'granted'} */
let permissionState = 'not_available';

const urlParams = new URLSearchParams(window.location.search);
const extensionId = urlParams.get('ext_id');

function showLoading() {
  document.getElementById('loading').classList.add('show');
}

function hideLoading() {
  document.getElementById('loading').classList.remove('show');
}

function showStatus(message, type) {
  const statusDiv = document.getElementById('statusMessage');
  statusDiv.innerHTML = message;
  statusDiv.className = `status-message ${type} show`;
}

async function requestMicrophonePermission() {
  if (permissionState !== 'not_available') {
    // Already granted or requested
    return;
  }
  permissionState = 'requesting';
  showLoading();

  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });

    // Success! We have permission
    permissionState = 'granted';
    hideLoading();
    showStatus("✅ Microphone access granted! You're all set.", 'status-success');

    // Stop the stream (we were just testing permission)
    stream.getTracks().forEach(track => track.stop());

    chrome.runtime.sendMessage({ request: 'microphonePermission', status: 'allowed' });
  } catch (error) {
    permissionState = 'not_available';
    hideLoading();
    console.error('Microphone permission denied:', error);

    let errorMessage = 'Permission denied. Please check your browser settings.';

    if (error.name === 'NotAllowedError') {
      if (error.toString().includes('dismissed')) {
        // Allowed to retry
        errorMessage =
          'Microphone access was denied.<br/>Tap "Allow while visiting the site" to grant the access.';
      } else {
        // User clicked on "Never allow" - so they need to now manually re-enable it
        errorMessage =
          'Microphone access not available. Please visit <a class="permission-link" href="#">this link</a> and enable the Microphone permission.';
      }
    } else if (error.name === 'NotFoundError') {
      errorMessage = 'No microphone found. Please check your device settings.';
    } else if (error.name === 'NotSupportedError') {
      errorMessage = 'Microphone access is not supported in this browser.';
    }

    showStatus(errorMessage, 'status-error');
  }
}

function skipPermission() {
  if (permissionState !== 'granted') {
    chrome.runtime.sendMessage({ request: 'microphonePermission', status: 'denied' });
  }
}
window.addEventListener('beforeunload', () => {
  skipPermission();
});

// Request permission on page load/focus
window.addEventListener('focus', () => {
  if (permissionState === 'not_available') {
    // Only request if not already being requested
    requestMicrophonePermission();
  }
});
window.addEventListener('load', () => {
  requestMicrophonePermission();
});

document.body.addEventListener('mousedown', e => {
  /** @type {HTMLElement} */
  // @ts-ignore
  const target = e.target;
  if (target.classList?.contains('permission-link')) {
    // chrome-extension: protocol links need to be opened using Chrome APIs
    chrome.tabs.create({
      url: `chrome://settings/content/siteDetails?site=chrome-extension%3A%2F%2F${extensionId}#:~:text=Microphone`,
      active: true,
    });
  }
});
