name: Weekly Growth Report

on:
  schedule:
    # Run every Monday at 9:00 AM UTC (10:00 AM BST in summer, 9:00 AM GMT in winter)
    - cron: '0 9 * * 1'

  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to include in report'
        required: false
        default: '7'

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate growth report
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          DAYS=${{ github.event.inputs.days || '7' }}
          npx tsx scripts/growth-report.ts --days $DAYS --output growth-report.md

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: growth-report-${{ github.run_number }}
          path: growth-report.md
          retention-days: 90

      - name: Create GitHub Issue with report
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: '📊 Weekly Growth Report - ${{ github.run_number }}'
          content-filepath: growth-report.md
          labels: |
            metrics
            growth
            automated

      - name: Post to Slack (Optional)
        if: false  # Enable when Slack webhook is configured
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST $SLACK_WEBHOOK_URL \
            -H 'Content-Type: application/json' \
            -d "{\"text\": \"📊 Weekly Growth Report generated: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
