/**
 * Message Types for Agent Mesh
 */

export const MESSAGE_TYPES = {
  // Context exchange
  REQUEST_CONTEXT: 'REQUEST_CONTEXT',
  PROVIDE_CONTEXT: 'PROVIDE_CONTEXT',

  // Recommendations
  ASK_RECOMMENDATION: 'ASK_RECOMMENDATION',
  OFFER_RECOMMENDATION: 'OFFER_RECOMMENDATION',

  // Negotiation
  NEGOTIATION_START: 'NEGOTIATION_START',
  NEGOTIATION_RESPONSE: 'NEGOTIATION_RESPONSE',

  // Escalation
  ESCALATION: 'ESCALATION',

  // Signals
  OPPORTUNITY: 'OPPORTUNITY',
  RISK_DETECTED: 'RISK_DETECTED',
  CREATIVE_SIGNAL: 'CREATIVE_SIGNAL',
  STRATEGY_SIGNAL: 'STRATEGY_SIGNAL',

  // System-specific hints
  AUTOPILOT_HINT: 'AUTOPILOT_HINT',
  MAL_HINT: 'MAL_HINT',
  COACHOS_HINT: 'COACHOS_HINT',
  IDENTITY_HINT: 'IDENTITY_HINT',
  CMG_HINT: 'CMG_HINT',
  MIG_HINT: 'MIG_HINT',
  SCENES_HINT: 'SCENES_HINT',
  AWARENESS_ALERT: 'AWARENESS_ALERT',

  // Team coordination
  TEAM_FORMATION: 'TEAM_FORMATION',
  TEAM_DISSOLUTION: 'TEAM_DISSOLUTION',
  TASK_DELEGATION: 'TASK_DELEGATION',
  TASK_COMPLETION: 'TASK_COMPLETION',
} as const;

export type MessageType = keyof typeof MESSAGE_TYPES;
