#!/bin/bash
# Deployment script for workspace migrations
# Run these SQL files manually in Supabase Dashboard → SQL Editor

echo "====================================================="
echo "WORKSPACE MIGRATIONS - MANUAL DEPLOYMENT GUIDE"
echo "====================================================="
echo ""
echo "The workspace migrations need to be deployed manually via Supabase Dashboard."
echo ""
echo "📍 Location: https://supabase.com/dashboard/project/YOUR_PROJECT/sql/new"
echo ""
echo "Run these SQL files in order:"
echo ""
echo "1️⃣  Migration 001: Cross-App Workspaces (Rename teams → workspaces)"
echo "   File: supabase/migrations/20251120000001_cross_app_workspaces.sql"
echo "   Size: 10KB"
echo ""
echo "2️⃣  Migration 002: Intel Contacts Table (Audio Intel persistent storage)"
echo "   File: supabase/migrations/20251120000002_intel_contacts_table.sql"
echo "   Size: 7.6KB"
echo ""
echo "3️⃣  Migration 003: Pitch Workspace Migration (UUID + workspace support)"
echo "   File: supabase/migrations/20251120000003_pitch_workspace_migration.sql"
echo "   Size: 14KB"
echo "   ⚠️  INCLUDES migrate_pitch_to_workspaces() function"
echo ""
echo "4️⃣  Migration 004: Unified Contact Registry (Cross-app contact linking)"
echo "   File: supabase/migrations/20251120000004_unified_contact_registry.sql"
echo "   Size: 14KB"
echo ""
echo "====================================================="
echo "DEPLOYMENT STEPS:"
echo "====================================================="
echo ""
echo "Step 1: Open each SQL file and copy its contents"
echo "Step 2: Paste into Supabase Dashboard → SQL Editor"
echo "Step 3: Click 'Run' to execute"
echo "Step 4: Verify success (should see 'Success. No rows returned')"
echo "Step 5: Move to next migration"
echo ""
echo "After all 4 migrations:"
echo ""
echo "Step 6: Run data migration function:"
echo "   SELECT * FROM migrate_pitch_to_workspaces();"
echo ""
echo "Step 7: Verify migration results:"
echo "   SELECT COUNT(*) FROM contacts WHERE workspace_id IS NULL;"
echo "   SELECT COUNT(*) FROM pitches WHERE workspace_id IS NULL;"
echo "   (Both should return 0)"
echo ""
echo "Step 8: Regenerate TypeScript types:"
echo "   cd packages/core-db"
echo "   bash scripts/generate-types.sh"
echo ""
echo "====================================================="
echo ""
echo "📝 Each SQL file includes rollback scripts at the bottom if needed."
echo ""
