#!/usr/bin/env tsx
/**
 * CLI tool to check context usage and suggest reset if needed
 * Usage: pnpm tsx .claude/workflow/context/check-context.ts
 */

import * as fs from 'fs';
import { analyzeContext, getConfig } from './tracker';

// ANSI color codes
const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  green: '\x1b[32m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

function main() {
  try {
    const config = getConfig();

    if (!config.enabled) {
      console.log(`${colors.yellow}⚠️  Context monitoring is disabled${colors.reset}`);
      process.exit(0);
    }

    const analysis = analyzeContext();

    if (analysis.shouldSuggestReset) {
      // Create reminder file
      const reminderContent = `# ⚠️ Context Reset Recommended

**Session Metrics:**
- File reads: ${analysis.usage.fileReads}
- File writes: ${analysis.usage.fileWrites}
- Tool calls: ${analysis.usage.toolCalls}
- Session age: ${Math.floor((Date.now() - analysis.usage.sessionStart) / 1000 / 60)} minutes

**Reasons for Reset:**
${analysis.reasons.map(r => `- ${r}`).join('\n')}

**Recommendations:**
${analysis.recommendations.map(r => `- ${r}`).join('\n')}

**How to Reset:**
1. Type \`/clear\` in Claude Code
2. Start fresh with clean context
3. This file will auto-delete after reset

---

*This file was auto-generated by the context monitoring system.*
*Delete this file manually if you want to suppress the warning.*
`;

      fs.writeFileSync(config.reminderFile, reminderContent);

      console.log(`${colors.yellow}⚠️  Context Reset Recommended${colors.reset}\n`);
      console.log(`${colors.cyan}Session Metrics:${colors.reset}`);
      console.log(`  File reads: ${analysis.usage.fileReads}`);
      console.log(`  File writes: ${analysis.usage.fileWrites}`);
      console.log(`  Session age: ${Math.floor((Date.now() - analysis.usage.sessionStart) / 1000 / 60)} minutes\n`);

      console.log(`${colors.yellow}Reasons:${colors.reset}`);
      analysis.reasons.forEach(reason => {
        console.log(`  • ${reason}`);
      });

      console.log(`\n${colors.green}Recommendations:${colors.reset}`);
      analysis.recommendations.forEach(rec => {
        console.log(`  • ${rec}`);
      });

      console.log(`\n${colors.blue}ℹ️  Reminder file created: ${config.reminderFile}${colors.reset}\n`);
    } else {
      console.log(`${colors.green}✅ Context usage is healthy${colors.reset}\n`);
      console.log(`${colors.cyan}Current Metrics:${colors.reset}`);
      console.log(`  File reads: ${analysis.usage.fileReads} / ${config.thresholds.maxFileReads}`);
      console.log(`  File writes: ${analysis.usage.fileWrites} / ${config.thresholds.maxFileWrites}`);
      console.log(`  Session age: ${Math.floor((Date.now() - analysis.usage.sessionStart) / 1000 / 60)} / ${config.thresholds.maxSessionMinutes} minutes\n`);
    }

    process.exit(0);
  } catch (error) {
    console.error(`${colors.red}❌ Error checking context:${colors.reset}`, error);
    process.exit(0); // Exit 0 even on error - never fail
  }
}

main();
